namespace dotnettables
{
    public static class JsonSchema
    {
        public const string ConntrackSchema = "{\"type\" : \"object\",\"properties\" : {\"match\": {\"type\" : \"object\",\"properties\" : {\"op\" : {\"type\" : \"string\",\"enum\": [\"==\"]},\"left\" : {\"type\" : \"object\",\"properties\": {\"ct\" : {\"type\" : \"object\",\"properties\": {\"key\" : {\"type\" : \"string\",\"enum\": [\"state\"]}},\"required\": [\"key\"]}},\"required\" : [\"ct\"]},\"right\" : {\"type\": \"string\",\"enum\": [\"invalid\", \"established\", \"related\", \"new\", \"untracked\"]}},\"required\" : [\"op\", \"left\", \"right\"]}},\"required\" : [\"match\"]}";
        public const string ICMPTypeSchema = "{\"type\" : \"object\",\"properties\" : {\"match\": {\"type\" : \"object\",\"properties\" : {\"op\" : {\"type\" : \"string\",\"enum\": [\"==\"]},\"left\" : {\"type\" : \"object\",\"properties\": {\"payload\" : {\"type\" : \"object\",\"properties\": {\"protocol\" : {\"type\" : \"string\",\"enum\": [\"icmp\"]},\"field\" : {\"type\" : \"string\",\"enum\" : [\"type\"]}},\"required\": [\"protocol\", \"field\"]}},\"required\" : [\"payload\"]},\"right\" : {\"type\":\"integer\"}},\"required\" : [\"op\", \"left\", \"right\"]}},\"required\" : [\"match\"]}";
        public const string IPAddressMatchSchema = "{\"type\": \"object\",\"properties\": {\"match\": {\"type\": \"object\",\"properties\": {\"op\": {\"type\": \"string\",\"enum\": [\"==\"]},\"left\": {\"type\": \"object\",\"properties\": {\"payload\": {\"type\": \"object\",\"properties\": {\"protocol\": {\"type\": \"string\",\"enum\": [\"ip\"]},\"field\": {\"type\": \"string\",\"enum\": [\"saddr\",\"daddr\"]}},\"required\": [\"protocol\",\"field\"]}},\"required\": [\"payload\"]},\"right\": {\"type\": \"string\"}},\"required\": [\"op\",\"left\",\"right\"]}},\"required\": [\"match\"]}";
        public const string IPVersionMatchSchema = "{\"type\" : \"object\",\"properties\" : {\"match\": {\"type\" : \"object\",\"properties\" : {\"op\" : {\"type\" : \"string\",\"enum\": [\"==\"]},\"left\" : {\"type\" : \"object\",\"properties\": {\"payload\" : {\"type\" : \"object\",\"properties\": {\"protocol\" : {\"type\" : \"string\",\"enum\": [\"ip\"]},\"field\" : {\"type\" : \"string\",\"enum\" : [\"version\"]}},\"required\": [\"protocol\", \"field\"]}},\"required\" : [\"payload\"]},\"right\" : {\"type\":\"integer\",\"enum\": [4, 6]}},\"required\" : [\"op\", \"left\", \"right\"]}},\"required\" : [\"match\"]}";
        public const string PortMatchSchema = "{\"type\": \"object\",\"properties\": {\"match\": {\"type\": \"object\",\"properties\": {\"op\": {\"type\": \"string\",\"enum\": [\"==\"]},\"left\": {\"type\": \"object\",\"properties\": {\"payload\": {\"type\": \"object\",\"properties\": {\"protocol\": {\"type\": \"string\",\"enum\": [\"tcp\",\"udp\"]},\"field\": {\"type\": \"string\",\"enum\": [\"sport\",\"dport\"]}},\"required\": [\"protocol\",\"field\"]}},\"required\": [\"payload\"]},\"right\": {\"type\": \"integer\"}},\"required\": [\"op\",\"left\",\"right\"]}},\"required\": [\"match\"]}";
        public const string ProtocolMatchSchema = "{\"type\" : \"object\",\"properties\" : {\"match\": {\"type\" : \"object\",\"properties\" : {\"op\" : {\"type\" : \"string\",\"enum\": [\"==\"]},\"left\" : {\"type\" : \"object\",\"properties\": {\"payload\" : {\"type\" : \"object\",\"properties\": {\"protocol\" : {\"type\" : \"string\",\"enum\": [\"ip\"]},\"field\" : {\"type\" : \"string\",\"enum\" : [\"protocol\"]}},\"required\": [\"protocol\", \"field\"]}},\"required\" : [\"payload\"]},\"right\" : {\"type\":\"string\",\"enum\": [\"tcp\", \"udp\", \"icmp\"]}},\"required\" : [\"op\", \"left\", \"right\"]}},\"required\" : [\"match\"]}";
        public const string AcceptStatementSchema = "{\"type\": \"object\",\"properties\": {\"accept\": {\"type\": \"null\"}},\"required\": [\"accept\"]}";
        public const string DropStatementSchema = "{\"type\": \"object\",\"properties\": {\"accept\": {\"type\": \"null\"}},\"required\": [\"drop\"]}";
        
    }
}